name: ippsra
channels:
  - menpo
  - conda-forge
dependencies:
  - python
  - pip
  - pip: 
    - opencv-python
    - opencv-contrib-python
    - pycodestyle
    - matplotlib
    - numpy
    - pandas
    - seaborn
