name: Style Check and Unittest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pycodestyle:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: ippsra
          environment-file: environment.yml
      - name: Run pycodestyle test
        run: pycodestyle $(git ls-files "*.py")

  run_unit_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: ippsra
          environment-file: environment.yml
      - name: Running unit tests
        run: |
          python -m unittest tests/unit/test_utils.py

  macos_unittest_pycodestyle:
    runs-on: macos-12
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: ippsra
          environment-file: environment.yml
      - name: Run pycodestyle test
        run: pycodestyle $(git ls-files "*.py")
      - name: Running unit tests
        run: |
          python -m unittest tests/unit/test_utils.py

  windows_unittest_pycodestyle:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: ippsra
          environment-file: environment.yml
      - name: Run pycodestyle test
        run: pycodestyle $(git ls-files "*.py")
      - name: Running unit tests
        run: |
          python -m unittest tests/unit/test_utils.py
