name: Style Check and Unittest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  functional_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
  codestyle:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: hw7
          environment-file: environment.yaml
      - run: pycodestyle $(git ls-files "*.py")
  run_unit_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run the projects setup.
        run: ./tests/unit/unittest.sh
