name: Unit and Func Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  functional_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: ippsra
        - run: |
          tests/func/test_func.sh

